---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bash

inputs:
- name: self-update-src

outputs:
- name: pipelines

params:
  TEAM: ((team))

run:
  path: self-update-src/tasks/collect-pipelines.sh
